#include "nsIAutoCompleteSearch.idl"
[ptr] native nsNativeStringArray(nsStringArray);


[scriptable, uuid(3A6BB324-512A-4d41-AC56-C8B8249A2E45)]
interface nsIAutoCompleteSearchStringArray : nsIAutoCompleteSearch
{
  boolean addStringEx( in AString strCategory, in AString strAdd, in AString strComment, in AString srtMathOnly);
  boolean addString( in AString strCategory, in AString strAdd);
  boolean deleteString( in AString strCategory, in AString strDelete);
  long sizeofArray( in AString strCategory );
  // returns the contents of an array as a single string using strSep as a separator
  AString contentsofArray( in AString strCategory, in AString strSep);
  void resetArray( in AString strCategory );
  void resetAll();
  void sortArray( in AString strCategory );
  void sortArrays();
  void viewArray( in AString strCategory);
  void setImplementation( in nsIAutoCompleteSearchStringArray imp);
  nsIAutoCompleteSearchStringArray getNewImplementation();
  nsIAutoCompleteSearchStringArray getGlobalSearchStringArray();
  [noscript]
  void setMarkedStrings( in nsNativeStringArray sa);
};

