// Copyright (c) 2004, MacKichan Software, Inc.  All rights reserved.

#include "nsISupports.idl"

[scriptable, uuid(a1d77ec2-17dc-46de-bd42-2324084b32a2)]
interface msiIMathMLEditRules : nsISupports
{
  void DummyFunction();
};
