MVR5
I*tciindetsR6"6%%"iG%%varsG%"zGF$F$C&>8%<"?(8$"""F/9#%%trueGC%>8&&9"6#F.@&-%%ty
peG6$F4%'vectorG>F4-%(convertG6$F4%%listG-F:6$F4%&arrayG>F4-F?6$F4%)listlistG>F
+-%&unionG6$F+-%&minusG6$-%*intersectG6$-%'indetsG6#F4-FT6$F4%)monomialG-FT6$F4
%)mathfuncG>F+-FN6$F+<#%*undefinedG-%'RETURNG6#F+F$F$F$F$,
I0tcisortedindetsRF$F$F$F$-F\o6#-%%sortG6#-F?6$-F"6#F6FAF$F$F$F$,
I'tcipwrR6$%#xxG%#nnG6,F&%"jG%"rG%"sG%"tG%"mG%"vG%"wG%"xG%"nGF$F$C->8'F/>8)F/>8
,-%%evalG6#9$>8--F`q6#9%@$-F:6$Fdq%'matrixGC$@$32F/-%'rowdimG6#Fdq2F/-%'coldimG
Fbr-F\o6#""!@&/F`rF/C$>F\qFdr>8*-%$rowG6$FdqF//FdrF/C$>F\qF`r>F^s-%$colGFas@$-F
:6$F^qF[r@&/-Far6#F^qF/C$>Fjp-FerF^t>8+-F`s6$F^qF//FatF/C$>FjpF]t>Fct-FgsFet@$3
2F/Fjp2F/F\qC%>8(-F[r6$FjpF\q?(F.F/F/FjpF1?(F+F/F/F\qF1>&Fau6$F.F+)&FctF7&F^sF]
o-F\o6#-F`q6#Fau@$3/FjpF/F^uC$@&FjrC$>Fau-F[r6$F/F\q?(F+F/F/F\qF1>&Fau6$F/F+)F^
qF[vFbsC$>Fau-F[r6$F\qF/?(F+F/F/F\qF1>&Fau6$F+F/F]wF\v@$3F]u/F\qF/C$@&F\tC$>Fau
-F[r6$F/Fjp?(F+F/F/FjpF1@%/FdqFhr>F[wF/>F[w)&FctF]oFdqFftC$>Fau-F[r6$FjpF/?(F+F
/F/FjpF1@%Fax>FdwF/>FdwFdxF\v@$3Fis-F:6$Fdq%(integerG@%/F]tFatC&@%2FhrFdqC$>F\q
Fdq>F4F^qC$>F\q,$Fdq!"">F4-%(inverseGF^t>Fau-FD6%%)identityG;F/-FarFU;F/-FerFU?
(F.F/F/F\qF1>Fau-%)multiplyG6$FauF4F\v-F\o6#-F`q6#-%$mapG6%R6$%"yGF(F$6$%)opera
torG%&arrowGF$)FbqFgqF$F$F$F^qFdq-F\o6#)-F`qF^tFdqF$F$F$F$,
I(tcimpy2R6$%"AG%"BG6%%"aG%"bGF`pF$F$C%>F.Fbq>F+Fgq@)35-%)tciismatGF7-%)tciisve
cGF75-F`]lF]o-Fb]lF]oC%>F4-F][lFhu@$533-F`]lFU/FizF//FgzF/3-Fb]lFU/-%(vectdimGF
UF/>F4&F46$F/F/F4F^]l-%*scalarmulGFhuFc]l-Fi^l6$F+F.*&F.F/F+F/F$F$F$F$,
I'tcimpyRF$6$F&FbpF$F$@%/F0FhrF/C%>F+F/?(F.F/F/F0F1>F+-Fa\l6$F+F5-F`qF]oF$F$F$F
$,
I(tciadd2R6$Fg\lFh\lF$F$F$@/3-F:6$FbqF[r-F:6$FgqF[r-%'mataddG6$FbqFgq3-F:6$FbqF
<-F:6$FgqF<Fb`lFf`l-Fc`l6$Fbq*&FgqF/-F<6$-Fd^lFaqF/F/Fh`l-Fc`l6$Fgq*&FbqF/-F<6$
-Fd^lFfqF/F/F^`l@%/-FerFaq-FarFaq-Fc`l6$Fbq-Fi^l6$-FD6%Fez;F/Fial;F/FhalFgq-Fc`
l6$Fbq-Fi^l6$-F[r6%FialFhalF/FgqF``l@%/-FerFfq-FarFfq-Fc`l6$Fgq-Fi^l6$-FD6%Fez;
F/F[cl;F/FjblFbq-Fc`l6$Fgq-Fi^l6$-F[r6%F[clFjblF/Fbq,&FbqF/FgqF/F$F$F$F$,
I'tciaddRF$F__lF$F$C%>F+Fhr?(F.F/F/F0F1>F+-Fi_lFg_lFh_lF$F$F$F$,
I*tciexpandRF$F$F$F$@%5-F:6$&F66#F/F[r-F:6$FhdlF<-F\o6#-Fd[l6%%'expandGF6%)symb
olicG-F\o6#-F`el6$F6FaelF$F$F$F$,
I*tcifactorRF$6&F&F_pFfpFcpF$F$C'@$5Fa_l2""#F0-%&ERRORG6#%:Wrong~number~of~argu
mentsG>F4Fhdl>FjpFhr@$/F0F]fl>Fjp&F66#F]fl@%5-F:6$F4F[rF9-F\o6#-Fd[l6%%(tcifac2
GF4Fjp-F\o6#-Fagl6$F4FjpF$F$F$F$,
I(tcifac2R6$FfpFcp6$Fbp%$ansGF$F$C%>F.F_q@'0FgqFhr@%-F:6$FgqFby>F+-%%modpG6$-%'
FactorGF7Fgq-F_fl6#%9Modulus~must~be~integer.G-F:6$F.Fby>F+-%(ifactorGF7>F+-%'f
actorGF7@%/F+.F.-F_fl6#%?Maple~only~factors~expressionsG-F\o6#Fh_lF$F$F$F$,
I(tcigcd2RF[`lF$F$F$@%3-F:6$FbqFbyF`hl-%%igcdGFd`l-%$gcdGFd`lF$F$F$F$,
I'tcigcdRF$F__lF$F$@%Fa_lFhrC%>F+Fhr?(F.F/F/F0F1>F+-F[jlFg_lFh_lF$F$F$F$,
I(tcilcm2RF[`lF$F$F$@%F^jl-%%ilcmGFd`l-%$lcmGFd`lF$F$F$F$,
I'tcilcmRF$F__lF$F$@%Fa_lFhrC%>F+Fhdl?(F.F/F/F0F1>F+-F][mFg_lFh_lF$F$F$F$,
I+tcihermiteR6#Fcp6#F'F$F$C%@$4F^`l-F_fl6#%:argument~must~be~a~matrixG>F.-FT6#-
F?6$Fhdl%$setG@%1F/-%%nopsGF7-%(hermiteG6$Fbq&F.Fidl-%)ihermiteGFaqF$F$F$F$,
I)tcismithRF^\mF_\mF$F$C%@$Fb\mFc\m>F.Fg\m@%F]]m-%&smithGFb]m-%'ismithGFaqF$F$F
$F$,
I(tcicondRF^\mF$F$F$-%&evalfG6#-%%condG6$FbqF]flF$F$F$F$,
I,tcicholeskyRF^\m6#F`pF$F$C$>F.-&%'linalgG6#%)choleskyGFaq-F\o6$-F`qF7-%*trans
poseGF7F$F$F$F$,
I2tcispectralradiusRF^\mF$F$F$-%$maxG6#-%*eigenvalsGFaqF$F$F$F$,
I)tciisvecR6#Ffp6#F&F$F$C$?(F.F/F/-F_]mFaqF1@$-F:6$-%#opG6$F.FbqF<-F\o6#F1-F\o6
#%&falseGF$F$F$F$,
I)tcidprodRFc\l6(Fg\lFh\l%#acG%#bcG%#arG%#brGF$F$C)>F.-%'tciargGFaq>F+-FjamFfq>
F43F_]l/-FerF7F/>Fjp3Fd]l/-FerF]oF/>Fau3F_]l/-FarF7F/>F\q3Fd]l/-FarF]oF/@13Fa]l
Fe]l-%(dotprodGFhu3Fau5FjpFe]lFh]l3F\q5F4Fa]l-F][lF[_l3F45F\qFe]lFecm3Fjp5FauFa
]lFh]l3FauF\q-F][l6$F.-Ff_mF]o3F4Fjp-F][l6$F+Fe_m-Fa\lFhuF$F$F$F$,
I)tcixprodRFc\lF[`lF$F$C%>F.Fiam>F+F\bm@%F^cm-%*crossprodGFhuFadmF$F$F$F$,
I'tciargR6#Fg\lFa`mF$F$@'F^`l@'/FialF/-F\o6#-F`s6$FbqF//FhalF/-F\o6#-FgsFcem-F\
oFaq-F:6$FbqFA-F\o6#-F?Fg`lFhemF$F$F$F$,
I'tcidivRF$6'FfpFg\lFh\l%"cGFapF$F$C$@'/F0""$>F.&F66#FefmFeflC%>F+-FT6#Fhdl>F4-
FT6#Fgfl@'/-F_]mF]oF/>F.-Fi`mF\w/-F_]mFUF/>F.-Fi`m6$F/F4C$>Fjp-FQ6$F+F4@%/-F_]m
6#FjpF/>F.-Fi`mF^x-F\o6#.%)needvarsG-F_fl6#%Opolynomial~divide~needs~two~or~thr
ee~argumentsG@'2-%'degreeG6$FhdlF.-F^im6$FgflF.-F\o6#*&FhdlF/FgflF^z-%'divideG6
%FhdlFgfl.FauF\v-F\o6#,&-%$quoG6%FhdlFgflF.F/*&-%$remGF^jmF/FgflF^zF/F$F$F$F$,
I-tcicompanionRF$6%%"pGFfpFg\lF$F$C%>F.-F`el6$FhdlFael@%Fefl>F+FgflC$>F4-FTF7@%
Fegm>F+FhgmFdhm-F\o6#-%*companionGFhuF$F$F$F$,
I(tcirootRF$6%%$varG%%vsetGFejmF$F$C&>F4Fhdl>F+FS@'Fefl>F.Fgfl/F0F/@%Fagm>F.Fdg
mFdhm-F_fl6#%Rpolynomial~root~finder~needs~one~or~two~argumentsG@%2-F^im6$F4F."
"&C$>%-_EnvExplicitGF1-%&solveGFh\n-%'fsolveG6%F4F.%(complexGF$F$F$F$,
I(tcisortRF$6$Fh[nFi[nF$F$C$@'Fefl>F.FgflF_\nC$>F+F[gm@%Fagm>F.FdgmFdhm-F_fl6#%
Kpolynomial~sort~needs~one~or~two~argumentsG-FcoF_imF$F$F$F$,
I+tcicombineR6$FfpFh[l6$F&F_pF$F$@%5F^`lFf`l-F\o6#-Fd[l6%%)tcicomb2GFbqFgq-F\o6
#-F[_nFd`lF$F$F$F$,
I)tcicomb2RFc^n6#FbpF$F$@-/FgqFhr-%(combineG6%Fbq%%trigGFael/FgqF/-Fe_n6%Fbq%$e
xpGFael/FgqF]fl-Fe_n6%Fbq%&powerGFael/FgqFefm-Fe_n6%Fbq%#lnGFael/Fgq""%-Fe_n6%F
bq%$PsiGFael-Fe_n6$FbqFaelF$F$F$F$,
I'getvarR6#%"eG6%F&F_pF`pF$F$C%@$/Fd`mF/C&@$-F:6$Fbq%)functionG-F\o6#-F[an6#-Fi
`m6$F/Fbq@$F^`lC$?(F.F/F/FialF1?(F+F/F/FhalF1C$>F4-F[an6#&FbqFhu@$0F4Fhr-F\oFUF
fr@$-F:6$Fbq%'symbolGFhemFfr?(F.Fd`mF^zF/F1C%@$-F:6$Fh`mF]cn-F\o6#Fh`m>F4-F[anF
dcn@$FhbnFibnFfrF$F$F$F$,
I+tciparfracRF$6%F&F_pFfpF$F$C$@$5F\flFa_l-F_fl6#%Cparfrac~needs~one~or~two~arg
umentsG@%FfdlC%>F4Fhdl?(F.F/F/FgzF1?(F+F/F/FizF1@%F_\n>&F4Fhu-%,tciparfrac2G6#F
hdn>Fhdn-Fjdn6$FhdnFgfl-F\o6#-F`qFU@%F_\n-F\o6#-FjdnF\gm-F\o6#-Fjdn6$FhdlFgflF$
F$F$F$,
I,tciparfrac2RF$F_\mF$F$@%F_\nC$>F.-F"F\gm@%/F^]mF/C$>F.-F?6$F.FA-F\o6#-F?6%Fhd
l%(parfracGFc]mFdhm-F\o6#-F?6%FhdlFjfnFgflF$F$F$F$,
I'tciintRF$F$F$F$@%Fedl-F\o6#-Fd[l6$%(tciint1GF6-F\o6#-FfgnFhoF$F$F$F$,
I(tciint1RF$6&Fh[n%$xQxG%%funcGFjglF$F$C(@$Fefl-F\o6#-%$intGFien@$/F0Fe`nC%>F4-
F`q6#-%%subsG6$/FgflF+Fhdl>Fjp-Fdhn6$F4/F+;Fgfm&F66#Fe`n-F\o6#-%)simplifyG6#-F`
q6#-F\in6$/F+FgflFjp>F.-F[anF\gm@$3F_\n0F.Fhr-F\o6#-FdhnF_im@$FdfmC%>F4-F`q6#-F
\in6$/F.F+Fhdl>Fjp-Fdhn6$F4/F+;FgflFgfm-F\o6#-Fiin6#-F`q6#-F\in6$/F+F.Fjp-F_fl6
#%Ewrong~number~of~arguments~in~tciint1GF$F$F$F$,
I'tcisumRF$6$Fh[n%&mapitGF$F$C)@%Fa_l-F_fl6#%4Sum~has~no~argumentG>F+Fedl@$Fefl
@%F+-F\o6#-Fd[l6%%$sumGFhdlFgfl-F\o6#-Fa]oFien@$Ffhn@%F+-F\o6#-Fd[l6%Fa]oFhdl/F
gflFcin-F\o6#-Fa]o6$FhdlF[^o>F.Fajn@$Fcjn@%F+-F\o6#-Fd[l6%Fa]oFhdlF.-F\o6#-Fa]o
F_im@$Fdfm@%F+-F\o6#-Fd[l6%Fa]oFhdl/F.Fd[o-F\o6#-Fa]o6$FhdlF`_o-F\oF\gmF$F$F$F$,
I(tciprodRF$Fc\oF$F$C)@%Fa_l-F_fl6#%8Product~has~no~argumentG>F+Fedl@$Fefl@%F+-
F\o6#-Fd[l6%%(productGFhdlFgfl-F\o6#-Fd`oFien@$Ffhn@%F+-F\o6#-Fd[l6%Fd`oFhdlF[^
o-F\o6#-Fd`oF_^o>F.Fajn@$Fcjn@%F+-F\o6#-Fd[l6%Fd`oFhdlF.-F\o6#-Fd`oF_im@$Fdfm@%
F+-F\o6#-Fd[l6%Fd`oFhdlF`_o-F\o6#-Fd`oFd_oFe_oF$F$F$F$,
I)tcisolveRF$6)%#iiGF'Fh\lFg\lFgpFdpFjglF$F$C%@$2F0F/Ffr@)F_\nC'>F+-F"6#-Fi`m6$
F/Fhdl?(F.F]flF/-F_]mF\gmF1>F+-FK6$F+-F"6#-Fi`m6$F.Fhdl>F\qF+?(F.F/F/-F_]m6#F\q
F1C%>Fjp-Fi`m6$F.F\q>Fau-%'lengthGFahm@$32F]flFau-%'testeqG6$%#QUG-%*substringG
6$Fjp;,&FauF/F^zF/Fau>F+-FN6$F+<#Fjp@%/FbgmFcco>F^s-F^]n6$FhdlF+Fdhm3Ffdl-F:6$F
gflF<@%2-FerF\gm-FarF\gm>F^s-%*leastsqrsGFien>F^s-%)linsolveGFien3Ffdl-F:6$Fgfl
F[rC$>F4-F?F]fo@%F_fo>F^s-Fdfo6$FhdlF4>F^s-FgfoFago>F^s-F^]nFien@%/-F_]m6#7#F^s
Fhr-F\o6#.%&NoSolG-F\o6#-F`q6#F^sF$F$F$F$,
I(tcikillRF$6#FgboF$F$C$-%(readlibG6#%)unassignG?(F.F/F/F0F1-Fjho6#F5F$F$F$F$,
I(tceigenR6$Fg\lFgp6$%$vexGFjglF$F$C%>F+-Fc^m6#-%*EigenvalsG6$FbqF.@$Fc_n-F\o6#
-F`q6#-F?6$F+FA-F\o6#Fd_mF$F$F$F$,
I*tcidsolveR6&%%eqnsGF'%&namesG%(procnumGFehoF$F$C'?(F.F/F/-F_]m6#9&F1-Fjho6#-F
i`m6$F.F][p>(%$ftpG9'-%'dsolveG6%Fbq-F?6$FgqF[]m/F:%(numericG?(F.F/F/F[[pF1-%(t
ciasgnG6%F`[p-Fi`m6$F.FgqFc[p>(%(ftprefsGFe[p-F_]mFfq-F\o6#.F][pF$F$F$F$,
I(tciasgnR6%%&fnameG%&vnameG%&pnameGF$F$F$>Fbq-%(unapplyG6$-.%*getodevalG6$Fgq-
Fi\p6#F]hnF]hnF$F$F$F$,
I.tcidelodeprocR6#FhjoF$F$F$@%2F/(Fe\pFbq>F_^p,&F_^pF/F^zF/C$/F_^pFhr-Fjho6#(Fd
[pFbqF$F$F$F$,
I*getodevalR6$%(thenameG%'thesetGFa`mF$F$C$?(F.F/F/Ff\pF1@$/-%$lhsG6#Fa\p.Fbq-F
\o6#-%$rhsGFb_p-F_fl6#.4%&foundGF$F$F$F$,
I+tcideftestRF\emF$F$F$C&@$Fb\mFc\m@$4-%&equalG6$Fbq-Fd[l6$%*conjugateGFbq-F_fl
6#%4matrix~must~be~realG@$4-Fd`p6$Fbq-Ff_mFaq-F_fl6#%9matrix~must~be~symmetricG
@+/-%)definiteG6$Fbq.%-negative_defGF1-F\o6#%'negdefG/-Fgap6$Fbq.%-positive_def
GF1-F\o6#%'posdefG/-Fgap6$Fbq.%1positive_semidefGF1-F\o6#%&psdefG/-Fgap6$Fbq.%1
negative_semidefGF1-F\o6#%&nsdefG-F\o6#%&indefGF$F$F$F$,
I)tciprimeR6%%"fG%#vvGFgp6)FfpFjgl%&ftempGFgbo%#jjGFh[nF]pF$F$C)>F\q-Fi`m6$;F/F
^zFgq@$/F][pFhr-F\o6#-FbqF^do@$-F:6$F][pFA-F\o6#--&%"DG6#-Fi`m6$FedpF][pFaqF^do
@$4-%)assignedG6#-FbqF7-F\o6#---%#@@G6$FcepF][pFaqF^do@%5-F:6$F\fpF[r-F:6$F\fpF
<>F4-Fd[l6%%%diffGF\fp-%"$GFa[p>F4-Fiin6#-F]gp6$F\fpF^gp@$2Fhr-%+searchtextG6$F
]gp-F?6$F4%'stringG-F_fl6#%EMaple~cannot~do~this~differentiationG@%-F:6$F\qF[rC
%>F+-F[r6$-FarF^do-FerF^do?(FjpF/F/FghpF1?(FauF/F/FhhpF1C$>F.&F\q6$FjpFau>&F+F^
ipFaenFiil-F\o6#-F\in6$/F.F\qFaenF$F$F$F$,
I(tcidiffRF$F$F$F$@%Fedl-F\o6#-Fd[l6$F]gpF6-F\o6#-Fiin6#-F]gpFhoF$F$F$F$,
I,tcisimplifyRF$F$F$F$@%Fedl-F\o6#-Fd[l6%FiinF6Fael-F\o6#-FiinFeelF$F$F$F$,
I+tcirewriteR6$%&ntypeG%#exGF$F$F$@9/FbqF/@%5F``lFh`l-Fd[l6%F?Fgq%)rationalG-F?
6$FgqFg[q/FbqF]fl-F?6$Fgq%&floatG/FbqFefm-F?6$FgqF[`n/FbqFe`n-F?6$Fgq%*factoria
lG/FbqFi\n-F?6$Fgq%&GAMMAG/Fbq""'-F?6$FgqFc`n/Fbq""(-F?6$Fgq%'sincosG/Fbq"")-F?
6$FgqFg_n/Fbq""*-F?6$Fgq%$tanG/Fbq"#5*&-%$absGFfqF/-F[`n6#*&F^z#F/F]fl-%)argume
ntGFfqF/F//Fbq"#6-%&evalcGFfq-F_fl6#%5Unknown~rewrite~typeGF$F$F$F$,
I5tciequationstomatrixRF$6%%"lGFgboFh[nF$F$C%>F4-F?6$&F66#F0FA@)Ffdl>F.-F?6$Fhd
lFAFjdl>F.Fi_q-F:Fj\m>F.Fi_q>F.7#-F_gp6$&F6F]o/F+;F/,&F0F/F^zF/-F\o6#-%*genmatr
ixG6%F.F4%%flagGF$F$F$F$,
I5tcimatrixtoequationsR6$Fd\lFdp6%Fg\lFh\lFh[nF$F$C$>F4-F?6$FgqFA@%Fgal-F\o6#-%
(geneqnsG6$FbqF4C%>F+-Fgs6$FbqFhal>F.-%(delcolsG6$Fbq;FhalFhal-F\o6#-Fhaq6%F.F4
F+F$F$F$F$,
I(tcifuncR6$F\dpFh[nF``mF$F$@%Fd[q-F\o6#-Fd[lFd`l-F\o6#-F`q6#-FbqFfqF$F$F$F$,
I(tcizmatR6$%&nrowsG%&ncolsG6#Fd\lF$F$C&>F.-%%bandG6$7#Fhr-Fj_mFd`l@$2FgqFbq>F.
-F`bq6$F.;,&FgqF/F/F/Fbq@$2FbqFgq>F.-%(delrowsG6$F.;,&FbqF/F/F/FgqFajoF$F$F$F$,
I(tciimatRFecqFhcqF$F$C&>F.-F\dq6$7#F/F_dq@$Fadq>F.Fcdq@$Fhdq>F.FjdqFajoF$F$F$F
$,
I)tciJBmatR6%%%diagGFfcqFgcqFhcqF$F$C&>F.-%,JordanBlockG6$Fbq-Fj_m6$FgqF][p@$2F
][pFgq>F.-F`bq6$F.;,&F][pF/F/F/Fgq@$2FgqF][p>F.-F[eq6$F.;FfdqF][pFajoF$F$F$F$,
I(tciBandR6%%*entrylistGFfcqFgcqFhcqF$F$C&>F.-F\dqFbfq@$Fffq>F.Fhfq@$F]gq>F.F_g
qFajoF$F$F$F$,
I(tcicorrRF$6)FgpFjglFd\lFgboF`dp%&list1G%&list2GF$F$@%3F_\nFfdlC(>F4Fhdl@$4-F:
6$Ff^lF\\p>F4-F[eq6$F4;F/F/>F.Fiz>F+-F[r6$F.F.?(FjpF/F/F.F1?(FauF/F/F.F1C%>F\q-
F?6$-FgsFeglFA>F^s-F?6$-Fgs6$F4FauFA>F`ip-Fc^m6#-&%)describeG6#%2linearcorrelat
ionG6$F\qF^sFiilFc\mF$F$F$F$,
I)tcicovarRF$6*FgpFcpFjglFd\lFgboF`dpF`hqFahqF$F$@%FchqC)>FjpFhdl@$4-F:6$&FjpFg
^lF\\p>Fjp-F[eq6$FjpF]iq>F.-FerFahm>F+-FarFahm>F4F`iq?(FauF/F/F.F1?(F\qF/F/F.F1
C&>F^s-F?6$-FgsF^ipFA>Fct-F?6$-FgsFcuFA>&F46$FauF\q-Fc^m6#-&Fcjq6#%+covarianceG
6$F^sFct@$2F/F.>Ff\r*(Ff\rF/F+F/,&F+F/F^zF/F^zF_enFc\mF$F$F$F$,
I*tcimomentRF$6'Fd\lFe\lFgp%%origGFgboF$F$C&@$2F0Fefm-F_fl6#%9moment~needs~3~ar
gumentsG>F4&F66#Fe`q>FjpFe_q@)FfdlC&>F.Fhdl@$4-F:6$&F.Fg^lF\\p>F.-F[eq6$F.F]iq>
F+-F?6$Fe_mFH@%-F:6$FjpF\\p-F\o6#-Fd[l6$&Fcjq6#&%'momentGFeglF+-F\o6#-Fd[l6$&Fc
jq6#&Fj_r6$F4%%meanGF+Fjdl@%Fa_r-F\o6#-Fg_r6#Fi_q-F\o6#-F_`rFh`r-F:Fj_q@%Fa_r-F
\o6#-Fg_rF\gm-F\o6#-F_`rF\gmC%>F.-FD6#;F/,&F0F/!"#F/?(FauF/F/FiarF1>&F.F_v&F6F_
v@%Fa_r-F\o6#-Fg_r6#Fdfn-F\o6#-F_`rFcbrF$F$F$F$,
I,tciquantileRF$6'Fd\lFe\l%%fracG%"qGFgboF$F$C&@$2F0F]fl-F_fl6#%;quantile~needs
~2~argumentsG>FjpFe_q>F4-F?6$FjpFg[q@)FfdlC&>F.Fhdl@$Ff^r>F.F[_r>F+F^_r-F\o6$Fj
p-Fd[l6$&Fcjq6#&%)quantileGFUF+Fjdl-F\o6$Fjp-F`drFh`rF\ar-F\o6$Fjp-F`drF\gmC%>F
.-FD6#Fd`q?(FauF/F/Fe`qF1>F]brF^br-F\o6$Fjp-F`drFcbrF$F$F$F$,
I(tcimeanRF$6%Fd\lFe\lFgboF$F$C$@$FjboFfr@)FfdlC&>F.Fhdl@$Ff^r>F.F[_r>F+F^_r-F\
o6#-Fc^m6#-Fi`m6#-Fd[l6$&Fcjq6#Fc`rF+Fjdl-F\o6#-Fc^m6#-FffrFh`rF\ar-F\o6#-Fc^m6
#-FffrF\gmC%>F.-FD6#;F/F0?(F4F/F/F0F1>&F.FU&F6FU-F\o6#-Fc^m6#-FffrFcbrF$F$F$F$,
I*tcimedianRF$FeerF$F$C$@$FjboFfr@)FfdlC&>F.Fhdl@$Ff^r>F.F[_r>F+F^_r-F\o6#-Fd[l
6$&Fcjq6#%'medianGF+Fjdl-F\o6#-F^irFh`rF\ar-F\o6#-F^irF\gmC%>F.Fdgr?(F4F/F/F0F1
>FigrFjgr-F\o6#-F^irFcbrF$F$F$F$,
I(tcimodeRF$6&Fd\lFe\lFgboFjglF$F$C$@$FjboFfr@)FfdlC(>F.Fhdl@$Ff^r>F.F[_r>F+F^_
r>Fjp7#-&Fcjq6#%%modeG6#Fdgm@$2F/Fbgm?(F4F]flF/FbgmF1>Fjp6$Fjp7#-F\[s6#-Fi`m6$F
4F+-F\oFahmFjdl-F\o6#-F\[sFh`rF\ar-F\o6#-F\[sF\gmC%>F.Fdgr?(F4F/F/F0F1>FigrFjgr
-F\o6#-F\[sFcbrF$F$F$F$,
I1tcigeometricmeanRF$FeerF$F$C$@$FjboFfr@)FfdlC&>F.Fhdl@$Ff^r>F.F[_r>F+F^_r-F\o
6#-Fc^m6#-Fd[l6$&Fcjq6#%.geometricmeanGF+Fjdl-F\o6#-Fc^m6#-Fh]sFh`rF\ar-F\o6#-F
c^m6#-Fh]sF\gmC%>F.Fdgr?(F4F/F/F0F1>FigrFjgr-F\o6#-Fc^m6#-Fh]sFcbrF$F$F$F$,
I0tciharmonicmeanRF$FeerF$F$C$@$FjboFfr@)FfdlC&>F.Fhdl@$Ff^r>F.F[_r>F+F^_r-F\o6
#-Fc^m6#-Fd[l6$&Fcjq6#%-harmonicmeanGF+Fjdl-F\o6#-Fc^m6#-F^`sFh`rF\ar-F\o6#-Fc^
m6#-F^`sF\gmC%>F.Fdgr?(F4F/F/F0F1>FigrFjgr-F\o6#-Fc^m6#-F^`sFcbrF$F$F$F$,
I(tcisdevRF$FeerF$F$C$@$FjboFfr@)FfdlC&>F.Fhdl@$Ff^r>F.F[_r>F+F^_r-F\o6#-Fc^m6#
-Fd[l6$&Fcjq6#&%2standarddeviationGFidlF+Fjdl-F\o6#-Fc^m6#-FdbsFh`rF\ar-F\o6#-F
c^m6#-FdbsF\gmC%>F.Fdgr?(F4F/F/F0F1>FigrFjgr-F\o6#-Fc^m6#-FdbsFcbrF$F$F$F$,
I(tcimdevRF$FeerF$F$C$@$FjboFfr@)FfdlC&>F.Fhdl@$Ff^r>F.F[_r>F+F^_r-F\o6#-Fd[l6$
&Fcjq6#%.meandeviationGF+Fjdl-F\o6#-FidsFh`rF\ar-F\o6#-FidsF\gmC%>F.Fdgr?(F4F/F
/F0F1>FigrFjgr-F\o6#-FidsFcbrF$F$F$F$,
I,tcivarianceRF$FeerF$F$C$@$FjboFfr@)FfdlC&>F.Fhdl@$Ff^r>F.F[_r>F+F^_r-F\o6#-Fc
^m6#-Fd[l6$&Fcjq6#&%)varianceGFidlF+Fjdl-F\o6#-Fc^m6#-FifsFh`rF\ar-F\o6#-Fc^m6#
-FifsF\gmC%>F.Fdgr?(F4F/F/F0F1>FigrFjgr-F\o6#-Fc^m6#-FifsFcbrF$F$F$F$,
I+tcipolyfitRF$6*Fd\l%$degG%"CGFh\l%"SGFjgl%$keyGFgboF$F$C/@$4Fdfm-F_fl6#%:wron
g~number~of~argumentsG>F.Fhdl@$4-F:6$F.F[r-F_fl6#%;selection~must~be~a~matrixG>
F+Fgfl@$34-F:6$F+Fby2FhrF+-F_fl6#%Edegree~must~be~a~nonnegative~integerG@$4/F`b
mF]fl-F_fl6#%Dselection~must~be~a~2~column~matrixG@%Fg^r>F^s7$FfpFh[lC$>F^s-F?6
$-F`s6$F.F/FA>F.F[_r@$1FhbmF+>F+,&FhbmF/F^zF/>Fjp-F<6#,&F+F/F/F/>F4F^_r>F\q&Fjp
Fidl>Fau<#Fi[t@%/FgfmF/C$?(FctF/F/F+F1C$>F\q,&F\qF/*&&Fjp6#,&FctF/F/F/F/)&F^sFi
dlFctF/F/>Fau-FK6$Fau<#Fd\t-F\o6#-&%$fitG6#&%,leastsquareG6%F^s/&F^sFhflF\qFauF
UC$?(FctF/F/F+F1C$>F\q,&F\qF/*&Fd\tF/)Fg]tFctF/F/>FauFj\t-F\o6#-&Fa]t6#&Fd]t6%F
^s/Fh\tF\qFauFUF$F$F$F$,
I,tcimregressRF$6)FfhsFh\lFafm%"dGF&Fd\lFe\lF$F$C)@$FihsFjhs>F\qFhdl@$4FahpFbis
@$-F:6$&F\qFg^lF\\p-F_fl6#%9columns~must~be~labelledG>F.-F?6$-F`sFawFA>F\q-F[eq
6$F\qF]iq@%/FgfmFhrC&>F+-FgsFaw>F^s-F`bqF^`t@%/FgflFhrC%>F4-Fdfo6$F^sF+>FjpFhr?
(FauF]flF/FhhpF1>Fjp,&FjpF/*&F]brF/&F46#FaeoF/F/C'>F4-F<6$FghpF/>F^s-%'concatG6
$F4F^s>F4Fj`t>Fjp&F4Fidl?(FauF]flF/FhhpF1>Fjp,&FjpF/*&F]brF/&F4F_vF/F/-F\o6#/Fc
]mFjpC&>F+-Fgs6$F\qFhhp>F^s-F`bq6$F\q;FhhpFhhp@%Fg`tC%>F4Fj`t>FjpFhr?(FauF/F/,&
FhhpF/F^zF/F1>FjpF`btC'>F4Feat>F^sFhat>F4Fj`t>FjpF]bt?(FauF/F/FcctF1>Fjp,&FjpF/
*&F]brF/&F46#,&FauF/F/F/F/F/-F\o6#/&F.6#FhhpFjpF$F$F$F$,
I,tcistatplotRF$FhcqF$F$@%FchqC'>F.Fhdl@$F`js-F_fl6#%;matrix~must~have~2~column
sG@$Fg^r>F.-%'putkeyG6$F.Fgjs-%+regressionG6$F./Fh[l,&Fg\lF/*&Fh\lF/FfpF/F/-%)s
tatplotG6$F./Fh[l-F\in6$%"%GFhetFbjsF$F$F$F$,
I,tciaprxareaR6'%%exprGF]dp%%rngeG%%nintGF:6#Fh[nF$F$C%@%Fc_n>F.-F[anFaq>F.Fgq@
%/F.Fhr>F.FfpF$@-/9(F/-%(leftsumG6%Fbq/F.F][pFe[p/FbgtF]fl-%*middlesumGFegt/Fbg
tFefm-%)rightsumGFegt/FbgtFe`n-%(simpsonGFegt/FbgtFi\n-%*trapezoidGFegt-F_fl6#%
<no~such~integration~formulaGF$F$F$F$,
I-tcipotentialR6$Fg\lF'6'F&Fgp%$vecG%%possGFjglF$F$C%@)F^`l@'F_em>F4FbemFdem>F4
Fgem-F_fl6#%Bnon-vector~argument~for~potentialGFiem>F4F]fmFf`l>F4Fbq-F_fl6#%;ba
d~argument~for~potentialG>Fjp-%*potentialG6%F4FgqFhim@%/FjpF1F\vFfrF$F$F$F$,
I-tcivecpotentRFhht6&F&FjhtF[itFjglF$F$C%@)F^`l@'F_em>F+FbemFdem>F+FgemFfrFiem>
F+F]fmFf`l>F+FbqFfr>F4-%*vecpotentG6%F+Fgq.Fjp@%/F4F1-F\o6#-F`qFahmFfrF$F$F$F$,
I,tcijacobianRFhht6#FjhtF$F$C$@)F^`l@'F_em>F.FbemFdem>F.Fgem-F_fl6#%@Nonvector~
argument~for~JacobianGFiem>F.F]fmFf`l>F.Fbq-F_fl6#%:Bad~argument~for~JacobianG-
F\o6#-%)jacobianGFb\pF$F$F$F$,
I(tcicurlRFhhtFe[uF$F$C$@)F^`l@'F_em>F.FbemFdem>F.Fgem-F_fl6#%<Nonvector~argume
nt~for~curlGFiem>F.F]fmFf`l>F.Fbq-F_fl6#%6Bad~argument~for~curlG-F\o6#-%%curlGF
b\pF$F$F$F$,
I+tcidivergeRFhhtFe[uF$F$C$@)F^`l@'F_em>F.FbemFdem>F.Fgem-F_fl6#%BNonvector~arg
ument~for~divergenceGFiem>F.F]fmFf`l>F.Fbq-F_fl6#%<Bad~argument~for~divergenceG
-F\o6#-%(divergeGFb\pF$F$F$F$,
I+tcihessianRFhhtF$F$F$-F\o6#-%(hessianGFd`lF$F$F$F$,
I(tcigradRFhhtF$F$F$-F\o6#-%%gradGFd`lF$F$F$F$,
I-tcilaplacianRFhhtF$F$F$-F\o6#-%*laplacianGFd`lF$F$F$F$,
I-tciwronskianRF\em6$FjhtFh[nF$F$C%@)F^`l@'F_em>F.FbemFdem>F.Fgem-F_fl6#%3Nonve
ctor~argumentGFiem>F.F]fmFf`l>F.Fbq-F_fl6#%-Bad~argumentG@%Fefl>F+FgflC$>F+-F"F
7@%Fagm>F+FdgmFdhm-F\o6#-%*wronskianGFhuF$F$F$F$,
I-tcichangevarRF$FgftF$F$C&@$4Fefl-F_fl6#%=Not~2~arguments~in~ChangeVarG>F.-FN6
$F_fn-F"F_gm>F.Fdfn-F\o6#-%*changevarG6%FhdlFgflFc]mF$F$F$F$,
I+tciextremaRF$6&F'%$locGFjglF&F$F$C$@'5FeflF_\nC%>F.F,?(FjpF/F/F0F1>F.-FK6$F.-
F"6#&F6Fahm@%Fafn@%F_\n>F4-F`q6#-%(extremaG6&FhdlF,F..F+>F4-F`q6#-Fbdu6&FhdlFgf
lF.Fddu@%F_\nFdhm-F\o6#.%4needconstrainedvarsGFdfm>F4-F`q6#-Fbdu6&FhdlFgflFgfmF
ddu-F_fl6#%EWrong~number~of~arguments~in~ExtremaG-F\o6%F4.%#atGF+F$F$F$F$,
I(tcifrobRFhcq6$%"PG%"FGF$F$C$>F+-%*frobeniusG6$FbqFeil-F\o6%Fd_mFh_l-FazF7F$F$
F$F$,
I*tcijordanRFhcq6$F^fu%"JGF$F$C$>F+-%'jordanGFdfuFefuF$F$F$F$,
I&tciGSRFhcq6'Fh\l%&vectsGFafmFcepF&F$F$C->F.-F?6$F`apFH?(FauF/F/F^]mF1>(%#gsGF
au-F?6$-Fi`m6$FauF.F<>F+F,?(FauF/F/F^]mF1>F+-FK6$F+<#Fjgu>F+F_jo>F+-Fco6$F+%)le
xorderG>F4-%,GramSchmidtGF]o>FjpFhgm?(FauF]flF/FfgmF1>Fjp-%&stackG6$Fjp-Fi`mF^[
l>Fjp-Ff_mFahm-F\o6$Fb[u-F][l6$-FazFahmFbqF$F$F$F$,
I,tcisingvalsRFhcq6&Fe\lFh\l%&svalsGF&F$F$C'>F.-F][l6$Fbq-%+htransposeGFaq>F+<#
-F]`mF7>F4F,?(FjpF/F/FbgmF1>F4-FK6$F4<#-%%sqrtG6#-Fi`m6$FjpF+F_enF$F$F$F$,
I-tcinullspaceRFhcqF^\mF$F$C$@'Ff`l>F.-F?F_`lF^`l>F.Fbq-F_fl6#%Bargument~must~b
e~vector~or~matrixG-F\o6#-%*nullspaceGF7F$F$F$F$,
I(tcirankRFhcqF^\mF$F$C$@'Ff`l>F.Fi[vF^`l>F.FbqF[\v-F\o6#-%%rankGF7F$F$F$F$,
I'tciSVDRFhcq6*Fcp%"UGFcep%"VG%"EGF`pFafmF&F$F$C)@'Ff`l>F.Fi[vF^`l>F.FbqF[\v>F\
qFhbm>F^sF`bm>Fau-FccqFfjq>F4-Fc^m6#-%$SvdG6%F.F+Fjp?(FctF/F/-%$minGFfjqF1>&Fau
6$FctFct&F46#Fct-F\o6%Fh_lF^vFfiuF$F$F$F$,
I*tcifsolveRF$F_\mF$F$@'F_\n-F\o6#-F`]nF\gmFeflC$>F.F_fn-F\o6#-F`]n6%FhdlF.Fgfl
-F_fl6#%DWrong~number~of~arguments~in~fsolveGF$F$F$F$,
I*tciterateR6%F\dpFg\lFgp6%FgboFjht%%nextGF$F$C&>F+-F<6#F[gq>&F+FidlFgq?(F.F/F/
F][pF1C%>F4-F`q6#-Fbq6#&F+F7@$4-F:6$F4F\\p>F4-Fc^mFh`v>&F+6#,&F.F/F/F/F4FiilF$F
$F$F$,
I&tciQRR6#%"ZG6$Fd\lF[crF$F$C$>F.-%)QRdecompG6$Fbq/%"QGFddu-F\o6$Fh_lFd_mF$F$F$
F$,
I&tciLURFhav6%F_]vFejmF`_qF$F$C$>F.-%)LUdecompG6%Fbq/F^fuFddu/%"LG.F4-F\o6%Fh_l
FaenFd_mF$F$F$F$,
I*tcimixnumRF``m6$F]jmFajmF$F$C%>F.-%&truncGFaq>F+-FjbrFaq@'F^gtF[o/F+Fhr-F\oF7
-F\o6%F.%"#GF+F$F$F$F$,
I'tcimodR6$FfpFejmF$F$F$@'F^`l-Fd[l6%%(tcimod2GFbqFgqFf`lFedv-FgdvFd`lF$F$F$F$,
I(tcimod2RFcdv6$Fg\lFbpF$F$C$>F.-FTFfq@'/F^]mFhr-F\o6#-FdhlFd`lFafnC$>F+-Fi`m6$
F/F.-F\o6#-Fajm6%FbqFgqF+-F_fl6#%Fmodulus~can~have~at~most~one~variableGF$F$F$F
$,
I*tciexpdenR6$Ffp%#muGF$F$F$C$@$2FgqFhr-F_fl6#%6mean~must~be~positiveG-F\o6#-%*
piecewiseG6%2FbqFhrFhr-Fc^m6#*&-F[`n6#,$*&FbqF/FgqF^zF^zF/FgqF^zF$F$F$F$,
I+tciexpdistRFafvF$F$F$C$@$FefvFffv-F\o6#-F\gv6%F^gvFhr-Fc^m6#,&$F\^qF^zF/FbgvF
^zF$F$F$F$,
I*tciexpinvRFafvF$F$F$C%@$FefvFffv@$5F^gv2F/Fbq-F_fl6#%:argument~must~be~in~(0,
1)G-F\o6#,$*&FgqF/-Fc`n6#,&FahvF/FbqF^zF/F^zF$F$F$F$,
I*tcihypdenR6&Ffp%"NGFehsFgpF$F$F$-F\o6#-Fc^m6#*(-%)binomialG6$F][pFbqF/-F]jv6$
,&FgqF/F][pF^z,&Fe[pF/FbqF^zF/-F]jv6$FgqFe[pF^zF$F$F$F$,
I+tcihypdistRFeiv6#%$totGF$F$C$>F.-Fa]o6$-Fc^m6#*&-F]jv6$F][p%"kGF/-F]jv6$Fajv,
&Fe[pF/Fb[wF^zF//Fb[w;FhrFbq-F\o6#*&F.F/FcjvF^zF$F$F$F$,
I*tcihypinvRFeiv6$FhjvFb[wF$F$@%2Fbq*&F][pF/FgqF^zC$>F.Fhr?(F+FhrF/Fe[pF1C$>F.,
&F.F/-Fc^m6#*(-F]jv6$F][pF+F/-F]jv6$Fajv,&Fe[pF/F+F^zF/FcjvF^zF/@$1FbqF.F[oC$>F
.Fahv?(F+FhrF/Fe[pF1C$>F.,&F.F/-Fc^m6#*(-F]jv6$F][pF^]wF/-F]jv6$FajvF+F/FcjvF^z
F^z@$1F.Fbq-F\o6#F^]wF$F$F$F$,
I*tcibininvR6%FfpFgpFejm6&Fb[wF_fu%&ratioGFhjvF$F$C%@$51F][pFhr1F/F][pFihv>F4*&
F][pF/,&F/F/F][pF^zF^z@%2FbqF][pC%>F+)F^_wFgq>FjpFhr?(F.FhrF/FgqF1C$>Fjp,&FjpF/
*&F+F/-Fc^m6#*&-F]jv6$FgqF.F/)F4F.F/F/F/@$1FbqFjpF]dvC%>F+)F][pFgq>FjpFahv?(F.F
hrF/FgqF1C$>Fjp,&FjpF/*&F+F/-Fc^m6#*&-F]jv6$Fgq,&FgqF/F.F^zF/)F4,$F.F^zF/F/F^z@
$1FjpFbq-F\o6#F`awF$F$F$F$,
I+tcirandbinR6%FgpFejmFfivFe[uF$F$C$>F.-&%'randomG6#&%(uniformG6$FhrFahvF\[p-F\
o6#-Fi`m6#-Fd[l6&Fb^w7#F.FbqFgqF$F$F$F$,
I/tcirandpoissonR6$Fg\lFfivFe[uF$F$C$>F.7#-&F^bw6#&%(poissonGFaqFfq-F\o6#-Fi`m6
#-Fd[l6%F?F.%)fractionGF$F$F$F$,
I-tcicauchydenR6%FfpFg\lFh\l6#%$denGF$F$C$>F.*(%#PiGF/F][pF/,&F/F/*&,&FbqF/FgqF
^zF]flF][pFjarF/F/-F\o6#-Fc^m6#,$*$F.F^z$F/FhrF$F$F$F$,
I,tcicharpolyRF$6%FdpFb[wF'F$F$C&@$5FjboF\flFjhs@$4Ffdl-F_fl6#%6argument~not~a~
matrixG@&F_\nC%>F4Fg\m>F.%"XG?(F+F/F/FfgmF1@$2Fhr-%+SearchTextG6$F^fw-Fi`mF]hmF
dhmFefl>F.Fgfl-%)charpolyGF_imF$F$F$F$,
I+tciminpolyRF$FaewF$F$C&@$FdewFjhs@$FfewFgew@&F_\nC%>F4Fg\m>F.F^fw?(F+F/F/Ffgm
F1@$FafwFdhmFefl>F.Fgfl-%(minpolyGF_imF$F$F$F$,
I'tcimaxRF$F_\mF$F$@'3F_\n555F\`qF\arFfdlFjdlC$>F.Fi\m-F\o6#-Fj_m6#-Fi`m6$FedpF
.3-F:6$Fhdl%(booleanG-F:6$FgflFihw-F\o6#5-%&evalbGF\gm-F`iwF_gm-Fj_mFhoF$F$F$F$,
I'tciminRF$F_\mF$F$@'FjgwC$>F.Fi\m-F\o6#-Fb^vFchwFfhw-F\o6#3F_iwFaiw-Fb^vFhoF$F
$F$F$,
I+tcirandmatR6&%#nrG%#ncGF:%&rangeG6%Fd\lFe\lFb[wF$F$C$@*/F][pF/>F.-%+randmatri
xG6%FbqFgq/%(entriesG-%%randG6#Fe[p/F][pF]flC$>F.-F[[x6&FbqFgq%*symmetricGF][x@
$4/FbqFgq-F_fl6#%8must~be~a~square~matrixG/F][pFefmC$>F.-F[[x6&FbqFgq%.antisymm
etricGF][x@$Fi[xF[\x/F][pFe`nC%>F.-F[[x6&FbqFgq%+unimodularGF][x>F+-%+randvecto
rG6$-Fb^vFd`lF][x?(F4F/F/F_]xF1>&F.6$F4F4&F+FUFajoF$F$F$F$,
I-tcirandmategR6&FbjwFcjw%&atypeG%'arangeG6&Fd\lFe\lFb[wF\dpF$F$C%>Fjp-%,tciran
dprocGFa[x@*Fhjw>F.-F[[x6%FbqFgq/F^[xFjpFb[xC$>F.-F[[x6&FbqFgqFg[xFc^x@$Fi[xF[\
xF^\xC$>F.-F[[x6&FbqFgqFc\xFc^x@$Fi[xF[\xFe\xC%>F.-F[[x6&FbqFgqFj\xFc^x>F+-F]]x
6$F_]xFc^x?(F4F/F/F_]xF1>Fb]xFd]xFd_mF$F$F$F$,
I+tcisetseedR6#FgpF$F$F$C%>%(assignsG%!G>%+conditionsGF]`x>%&_seedGFbqF$6%Fa`xF
\`xF_`xF$F$,
I(tcirandRF$6(FapFgp%#d1G%#d2GFg\lFh\lF$F$@'Fa_l-F`[xF$F_\n@%F\`qC'>F.Fhdl>F+Fh
r?(F$F/F/F$0F.F,C$>F+Ff[t>F.-FN6$F.<#Fc]m>F+--F`[x6#;F/F+F$&FhdlF]o--F`[xF\gmF$
C%>Fau-Fb^v6$-%&floorGF\gm-FcbxF_gm>F\q-Fj_mFabx--F`[x6#;FauF\qF$F$F$F$F$,
I/tcirandfromsetR6#F^fw6$FapFgpF$F$@$F\`qC'>F.Fhdl>F+Fhr?(F$F/F/F$F_axC$>F+Ff[t
>F.Fcax>F+FgaxF[bxF$F$F$F$,
I,tcirandprocRF]cx6(FapFgpFdpFf`xFg`xFejmF$F$@&Fa_lFi`xF_\n@'F\`qC$>F\q-F?6$-%(
CompSeqG6#7#-.F[cxFaq%*procedureG-F`qF^doFjdlC$>F4Fhdl-F`[x6#;F]bt&F4FhflF]bxF$
F$F$F$,
I,tcidistinctRF$Fd^nF$F$C$?(F.F/F/F0F1?(F+FeavF/F0F1@$/F5Fb`qF]amF[amF$F$F$F$,
I,tcidostringR6#'FapF\hp6#%$strGF$F$C$>F.-%$catG6%%/if~(0=0)~then~GFbq%%~fi;G-%
&parseG6$F.%*statementGF$F$F$F$,
I(tciloopR6$'Fi`mF\hp'Ff^mF\hp6$%&countG%'errmsgGF$F$C%>F.Fhr-FfexFaq@$0-FedoFf
qFhrC'?(F$F/F/F$2F."$+$C&>%'mycondG-FdfxFfq@$F[hx-F\oF$Fagx>F.Feav>F\`xF]`x>F_`
xF]`x>F+-F_fx6$%>Could~not~satisfy~condition:~GFgq-F_flF]oF$6%F[hxF_`xF\`xF$F$,
I.tcisetassignsR6#'F[fxF\hpF$F$F$@%/-Fedo6#F\`xFhr>F\`xFbq>F\`x-F_fx6%F\`x%#;~G
FbqF$F_ixF$F$,
I1tcisetconditionsRFjhxF$F$F$@%/-Fedo6#F_`xFhr>F_`xFbq>F_`x-F_fx6%F_`x%&~and~GF
bqF$FjixF$F$,
I+tcisatisfyRF$F$F$F$C%@$0F^ixFhr@&Fhix-Fgfx6$F\`xQ%true6"Fdjx-Fgfx6$F\`xF_`x>F
\`xF]`x>F_`xF]`xF$F[[yF$F$,
I,tcipickunitRF[`lF$F$F$C$@$-F:6$Feq%"+G-F\o6#F_q-F\o6#FeqF$F$F$F$,
I)tciismatRF``mFa`mF$F$C$?(F.F/F/Fd`mF1@$-F:6$Fh`mF[rF[amF]amF$F$F$F$,
I0tciaddtranspairR6&F:%&itypeGF\dpF_fuF$F$F$C%-%%withG6#%)inttransG-%)addtableG
6'Fbq-F][pFa_n-Fe[p6#FapFbpFap-Fj\y6'FgqF]]yF\]yFapFbpF$F$F$F$
