// Copyright (c) 2006, MacKichan Software, Inc.  All rights reserved.

#include "nsISupports.idl"


%{C++
/**
 * The signature of the adjust caret callback function.
 * This is the function that will get called just before collaspe if called
 * callback is set with SetAdjustCaretFuncCallback.
 *
 * Implementers should return the following:
 *
 * @return NS_OK
 *
 */
typedef nsresult (*msiAdjustCaretCB)(void* msiEditor, nsIDOMEvent * mouseEvent, nsCOMPtr<nsIDOMNode> & node, PRInt32 &offset);
typedef nsresult (*msiSetSelectionCB)(void* msiEditor, nsCOMPtr<nsIDOMNode> & focusNode, PRInt32 focusOffset, 
                                      PRBool selecting, PRBool & preventDefault);
%}

native msiAdjustCaretCB(msiAdjustCaretCB);
native msiSetSelectionCB(msiSetSelectionCB);


/**
 * MSI Interface, an extension of nsISelection.idl, for manipulating and querying the current selected range
 * of nodes within the document.
 *
 * @status FROZEN
 * @version 1.0
 */
interface nsIDOMNode; 
interface nsIDOMEvent; 
 
[uuid(c0f3b745-26ba-466e-8f8e-e9c4a7c33d86)]
interface msiISelection : nsISupports
{
  const unsigned long  INVALID_OFFSET  = 0xFFFFFFFF;

  readonly attribute nsIDOMNode msiAnchorNode;
  readonly attribute unsigned long msiAnchorOffset;
  readonly attribute nsIDOMNode msiFocusNode;
  readonly attribute unsigned long msiFocusOffset;
  
  void Set(in nsIDOMNode startNode, in unsigned long startOffset,
           in nsIDOMNode endNode, in unsigned long endOffset,
           in nsIDOMNode focusNode, in unsigned long focusOffset,
           in nsIDOMNode anchorNode, in unsigned long anchorOffset);
  void GetMouseDown(out PRBool isDown);           
  void SetMouseDown(in  PRBool isDown);
  
  [noscript] void InitalizeCallbackFunctions(in msiAdjustCaretCB adjustCaretCB,
                                             in msiSetSelectionCB setSelectionCB,
                                             in voidPtr msiEditor);
  [noscript] void SetDOMEvent(in nsIDOMEvent mouseEvent);                                             
             
};
