<script type="application/x-javascript" src="chrome://prince/content/prince.js"/>
<script type="application/x-javascript" src="chrome://prince/content/msiEditorDefinitions.js"/>
<script type="application/x-javascript" src="chrome://prince/content/msiEditor.js"/>
<script type="application/x-javascript" src="chrome://prince/content/msiMainEditor.js"/>
<script type="application/x-javascript" src="chrome://prince/content/msiEditorUtilities.js"/>
<script type="application/x-javascript" src="chrome://prince/content/msiDialogUtilities.js"/>
<script type="application/x-javascript" src="chrome://prince/content/msiComposerCommands.js"/>
<script type="application/x-javascript" src="chrome://prince/content/fastcursor.js"/>
<script type="application/x-javascript" src="chrome://editor/content/EditorCommandsDebug.js"/>
<script type="application/x-javascript" src="chrome://prince/content/msiEditorCommandsDebug.js"/>
<script type="application/x-javascript" src="chrome://editor/content/StructBarContextMenu.js"/>
<script type="application/x-javascript" src="chrome://global/content/viewZoomOverlay.js"/>
<script type="application/x-javascript" src="chrome://prince/content/msiEditorApplicationOverlay.js"/>
<script type="application/x-javascript" src="chrome://prince/content/mainCore.js" />
