<menubar id="main-menubar" class="chromeclass-menubar" persist="collapsed" grippyhidden="false">
   <menu id="fileMenu" />
   <menu id="editMenu" />
   <menu id="insertMenu"/>
   <menu id="viewMenu" />
   <menu id="goMenu" />
   <menu id="tagMenu" />
   <menu id="MSITypesetMenu" />
   <menu id="toolsMenu" />
   <menu id="MSIComputeMenu" />
   <menu id="windowMenu" />
   <!-- DEBUG only -->
   <menu id="debugMenu" /> 
   <!-- end DEBUG only -->
   <menu id="helpmenu" />
</menubar>
