<!DOCTYPE window [
<!ENTITY % editorDTD SYSTEM "chrome://prince/locale/prince.dtd" >
%editorDTD;
<!ENTITY % editorOverlayDTD SYSTEM "chrome://editor/locale/editorOverlay.dtd" >
%editorOverlayDTD;
<!ENTITY % mathmlOverlayDTD SYSTEM "chrome://prince/locale/MathmlOverlay.dtd" >
%mathmlOverlayDTD;
<!ENTITY % computeOverlayDTD SYSTEM "chrome://prince/locale/computeOverlay.dtd" >
%computeOverlayDTD;
<!ENTITY % brandDTD SYSTEM "chrome://prince/locale/brand.dtd" >
%brandDTD;
<!ENTITY % fastcursorDTD SYSTEM "chrome://prince/locale/fastcursor.dtd" >
%fastcursorDTD;
<!ENTITY % princetoolbarsDTD SYSTEM "chrome://prince/locale/toolbarsOverlay.dtd" >
%princetoolbarsDTD;
]> 
