\MSITeXButtonReq{altaffilmark}
\MSITeXButtonReq{affil}
\MSITeXButtonReq{email}
\MSITeXButton{and}

%\MSITeXButton{sun}
%\MSITeXButton{earth}

\MSITeXButton{micron}
\MSITeXButton{sbond}
\MSITeXButton{dbond}
\MSITeXButton{tbond}
\MSITeXButton{diameter}
\MSITeXButton{arcdeg}
\MSITeXButton{sq}
\MSITeXButton{arcmin}
\MSITeXButton{arcsec}
\MSITeXButton{fd}
\MSITeXButton{fh}
\MSITeXButton{fm}
\MSITeXButton{fs}
\MSITeXButton{fdg}
\MSITeXButton{farcm}
\MSITeXButton{farcs}
\MSITeXButton{fp}
\MSITeXButton{onehalf}
\MSITeXButton{onethird}
\MSITeXButton{twothirds}
\MSITeXButton{onequarter}
\MSITeXButton{threequarters}
\MSITeXButton{ubvr}
\MSITeXButton{ub}
\MSITeXButton{bv}
\MSITeXButton{vr}
\MSITeXButton{ur}




\MSITeXButton{aj}
\MSITeXButton{actaa}
\MSITeXButton{araa}
\MSITeXButton{apj}
\MSITeXButton{apjl}
\MSITeXButton{apjs}
\MSITeXButton{ao}
\MSITeXButton{apss}
\MSITeXButton{aap}
\MSITeXButton{aapr}
\MSITeXButton{aaps}
\MSITeXButton{azh}
\MSITeXButton{baas}
\MSITeXButton{caa}
\MSITeXButton{cjaa}
\MSITeXButton{icarus}
\MSITeXButton{jcap}
\MSITeXButton{jrasc}
\MSITeXButton{memras}
\MSITeXButton{mnras}
\MSITeXButton{na}
\MSITeXButton{nar}
\MSITeXButton{pra}
\MSITeXButton{prb}
\MSITeXButton{prc}
\MSITeXButton{prd}
\MSITeXButton{pre}
\MSITeXButton{prl}
\MSITeXButton{pasa}
\MSITeXButton{pasp}
\MSITeXButton{pasj}
\MSITeXButton{qjras}
\MSITeXButton{rmxaa}
\MSITeXButton{skytel}
\MSITeXButton{solphys}
\MSITeXButton{sovast}
\MSITeXButton{ssr}
\MSITeXButton{zap}
\MSITeXButton{nat}
\MSITeXButton{iaucirc}
\MSITeXButton{aplett}
\MSITeXButton{apspr}
\MSITeXButton{bain}
\MSITeXButton{fcp}
\MSITeXButton{gca}
\MSITeXButton{qrl}
\MSITeXButton{jcp}
\MSITeXButton{jgr}
\MSITeXButton{jqsrt}
\MSITeXButton{memsai}
\MSITeXButton{nphysa}
\MSITeXButton{physrep}
\MSITeXButton{physscr}
\MSITeXButton{planss}
\MSITeXButton{procspie}













\MSITextElement{object}
\MSITextElement{objectname}



\MSITextElement{citep}
\MSITextElement{citet}


%% Finish up

\def\classcss{@import url("resource://app/res/css/article.css");}

\makeatother