
\msi@extrapi{%
  \msitag{<?sw-tagdefs href="resource://app/res/tagdefs/beamerdefs.xml" type="text/xml" ?>^^0a}
  \msitag{<?sw-xslt href="beamer.xsl" type="text/xml" ?>^^0a}
}

%\MSITextElement{usetheme}
%\MSITextElement{institute}

\def\classcss{%
   @import url("resource://app/res/css/article.css");
   @import url("resource://app/res/css/beamer.css");}

\input msi-beamer.sty % do we need a separate file?

\makeatother
