#include "nsISupports.idl"
#include "nsIDOMDocument.idl"

[scriptable, uuid(7BB5750B-BF2F-49d9-973E-403D489A602D)]
interface msiIScriptRunner : nsISupports
{
  attribute nsISupports ctx;
  void setContext( in nsIDOMDocument ctx);
   // executes the contents of str. Returns "" if successful, otherwise returns the string value of the exception.
  AString Eval( in AString str );
};